"""Paired writer-level bootstrap: ResNet-18 vs SmallCNN, on the public corpora.

Why paired, not marginal: ResNet-18 and SmallCNN were evaluated on the SAME
pairs from the SAME writers on each public corpus. results_rq2_eer_bootstrap_ci
.csv treats each model's interval independently, which throws away that shared
structure -- most of a marginal interval's width comes from which writers
landed in the (small) test split, a source of variance common to both models.
Resampling writers ONCE per iteration and taking the EER difference within
that resample cancels the shared component, giving a strictly more powerful
test of "is ResNet-18 worse than SmallCNN on this corpus" than comparing two
overlapping marginal intervals.

Reuses, unmodified:
    - scripts/bootstrap_cross_dataset_ci.py's `load_run` (CSV/JSON loading)
      and its importlib machinery for 03_results_analysis.py.
    - 03_results_analysis.py's `compute_eer` (via the above).
Neither of those two files is modified by this script.

Method, per public corpus (cedar, bhsig260_bengali, bhsig260_hindi) and per
metric (eer_all, eer_skilled):
    1. Load both models' test_scores.csv (via load_run).
    2. Verify row-for-row alignment (label, kind, writer_a, writer_b all
       identical between the two files) -- both were generated by the same
       generate_pairs(samples, seed=42+2) call, so they must match exactly.
       If they don't, STOP: an unpaired "paired" test is worse than none.
    3. Resampling universe = sorted unique writer_a (same anchor-writer
       convention as writer_bootstrap in 03_results_analysis.py).
    4. For each of 1000 iterations (seed 42): sample writers with
       replacement, build ONE pair mask from that resample, apply it to
       BOTH models, and compute d = EER(resnet18) - EER(smallcnn) with the
       same compute_eer for both (the estimator choice cancels in a
       difference).
    5. Report the observed difference (on the full, unresampled data), the
       2.5/97.5 percentiles of d, and the fraction of iterations with d > 0.

Usage (from project root):
    .\\.venv\\Scripts\\python.exe scripts\\paired_bootstrap_rq2.py ^
        --results-root "C:\\Users\\nehas\\Downloads\\results_eval"

Output:
    report/dataset_checks/results_rq2_paired_bootstrap.csv
"""

from __future__ import annotations

import argparse
import csv
import sys
from pathlib import Path

import numpy as np

PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT / "scripts"))

import bootstrap_cross_dataset_ci as bcci  # noqa: E402 -- reuse its loading/importlib machinery

load_run = bcci.load_run
compute_eer = bcci.compute_eer

DATASETS = ["cedar", "bhsig260_bengali", "bhsig260_hindi"]
EXPECTED_N_WRITERS = {"cedar": 11, "bhsig260_bengali": 20, "bhsig260_hindi": 32}
N_ITERATIONS = 1000
SEED = 42

MARGINAL_CI_CSV = PROJECT_ROOT / "report" / "dataset_checks" / "results_rq2_eer_bootstrap_ci.csv"


def _load_writer_b(run_dir: Path) -> np.ndarray:
    """Supplementary read of the writer_b column only, for the row-alignment
    check -- load_run() (reused above) doesn't return it, and this script
    must not modify bootstrap_cross_dataset_ci.py to add it there."""
    with (run_dir / "test_scores.csv").open(newline="", encoding="utf-8") as fh:
        rows = list(csv.DictReader(fh))
    return np.array([int(r["writer_b"]) for r in rows])


def _load_marginal_ci() -> dict:
    """dataset,metric -> row dict, from results_rq2_eer_bootstrap_ci.csv."""
    if not MARGINAL_CI_CSV.is_file():
        return {}
    with MARGINAL_CI_CSV.open(newline="", encoding="utf-8") as fh:
        rows = list(csv.DictReader(fh))
    return {(r["dataset"], r["metric"], r["backbone"]): r for r in rows}


def verify_alignment(resnet_run, smallcnn_run, dataset: str) -> None:
    dists_r, labels_r, kinds_r, writer_a_r, _ = resnet_run
    dists_s, labels_s, kinds_s, writer_a_s, _ = smallcnn_run

    problems = []
    if len(labels_r) != len(labels_s):
        problems.append(f"row count differs: resnet18={len(labels_r)} smallcnn={len(labels_s)}")
    else:
        if not np.array_equal(labels_r, labels_s):
            n_bad = int((labels_r != labels_s).sum())
            problems.append(f"{n_bad} label mismatches")
        if not np.array_equal(kinds_r, kinds_s):
            n_bad = int((kinds_r != kinds_s).sum())
            problems.append(f"{n_bad} kind mismatches")
        if not np.array_equal(writer_a_r, writer_a_s):
            n_bad = int((writer_a_r != writer_a_s).sum())
            problems.append(f"{n_bad} writer_a mismatches")
        wb_r, wb_s = _load_writer_b(RUN_DIRS[dataset]["resnet18"]), _load_writer_b(RUN_DIRS[dataset]["smallcnn"])
        if not np.array_equal(wb_r, wb_s):
            n_bad = int((wb_r != wb_s).sum())
            problems.append(f"{n_bad} writer_b mismatches")

    if problems:
        print(f"\n[STOP] {dataset}: rows are not aligned between the two "
              f"test_scores.csv files:")
        for p in problems:
            print(f"    - {p}")
        print("An unpaired \"paired\" test is worse than no test. Not proceeding.")
        sys.exit(1)


def paired_bootstrap(dists_r, dists_s, labels, writer_a,
                     n_iterations: int = N_ITERATIONS, seed: int = SEED) -> dict:
    """Resample writer identities ONCE per iteration; apply the same
    resample-derived pair mask to both models; return the distribution of
    EER(resnet18) - EER(smallcnn)."""
    rng = np.random.default_rng(seed)
    unique_writers = np.unique(writer_a)
    n_writers = len(unique_writers)

    diffs = []
    for _ in range(n_iterations):
        sampled = rng.choice(unique_writers, size=n_writers, replace=True)
        idx = np.concatenate([np.where(writer_a == w)[0] for w in sampled])
        y = labels[idx]
        try:
            eer_r, _ = compute_eer(dists_r[idx], y)
            eer_s, _ = compute_eer(dists_s[idx], y)
        except ValueError:
            continue  # degenerate resample (e.g. all one class) -- skip
        diffs.append(eer_r - eer_s)

    diffs = np.array(diffs)
    return {
        "diffs": diffs,
        "n_valid_iterations": int(len(diffs)),
        "n_test_writers": int(n_writers),
        "ci_lo": float(np.percentile(diffs, 2.5)),
        "ci_hi": float(np.percentile(diffs, 97.5)),
        "frac_resnet18_worse": float((diffs > 0).mean()),
    }


RUN_DIRS: dict = {}


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--results-root", required=True,
                    help="directory containing the seven eval_<backbone>_<dataset> "
                         "subdirectories (extracted results_eval.zip)")
    ap.add_argument("--out", default=None,
                    help="output CSV path (default: report/dataset_checks/"
                         "results_rq2_paired_bootstrap.csv)")
    args = ap.parse_args()

    results_root = Path(args.results_root)
    out_path = Path(args.out) if args.out else (
        PROJECT_ROOT / "report" / "dataset_checks" / "results_rq2_paired_bootstrap.csv"
    )

    marginal_ci = _load_marginal_ci()
    if not marginal_ci:
        print(f"[STOP] could not read {MARGINAL_CI_CSV} for verification step 1. "
              f"Run bootstrap_cross_dataset_ci.py first.")
        return 1

    for dataset in DATASETS:
        RUN_DIRS[dataset] = {
            "resnet18": results_root / f"eval_resnet18_{dataset}",
            "smallcnn": results_root / f"eval_smallcnn_{dataset}",
        }

    rows = []

    for dataset in DATASETS:
        print(f"\n=== {dataset} ===")
        resnet_run = load_run(RUN_DIRS[dataset]["resnet18"])
        smallcnn_run = load_run(RUN_DIRS[dataset]["smallcnn"])

        verify_alignment(resnet_run, smallcnn_run, dataset)
        print("  [alignment] OK -- rows identical (label, kind, writer_a, writer_b)")

        dists_r, labels, kinds, writer_a, metrics_r = resnet_run
        dists_s, _, _, _, metrics_s = smallcnn_run  # labels/kinds/writer_a identical, verified above

        skilled_mask = (kinds == "positive") | (kinds == "skilled")

        for metric_name, mask in (("eer_all", np.ones(len(labels), dtype=bool)),
                                  ("eer_skilled", skilled_mask)):
            d_r, d_s, y, w = dists_r[mask], dists_s[mask], labels[mask], writer_a[mask]

            eer_resnet18, _ = compute_eer(d_r, y)
            eer_smallcnn, _ = compute_eer(d_s, y)

            # ---- verification 1: match the marginal CSV's point_estimate ----
            key_r = (dataset, metric_name, "resnet18")
            key_s = (dataset, metric_name, "smallcnn")
            if key_r not in marginal_ci or key_s not in marginal_ci:
                print(f"[STOP] {dataset}/{metric_name}: no matching row in "
                      f"{MARGINAL_CI_CSV.name} -- cannot verify.")
                return 1
            expected_r = float(marginal_ci[key_r]["point_estimate"])
            expected_s = float(marginal_ci[key_s]["point_estimate"])
            if abs(eer_resnet18 - expected_r) > 1e-9 or abs(eer_smallcnn - expected_s) > 1e-9:
                print(f"[STOP] {dataset}/{metric_name}: point estimate mismatch "
                      f"vs {MARGINAL_CI_CSV.name}:")
                print(f"    resnet18:  here={eer_resnet18!r}  csv={expected_r!r}")
                print(f"    smallcnn:  here={eer_smallcnn!r}  csv={expected_s!r}")
                print("Masking or loading differs from bootstrap_cross_dataset_ci.py. "
                      "Not proceeding.")
                return 1

            observed_diff = eer_resnet18 - eer_smallcnn
            assert observed_diff == eer_resnet18 - eer_smallcnn  # verification 3, trivially

            boot = paired_bootstrap(d_r, d_s, y, w)

            # ---- verification 2: writer counts -------------------------
            expected_writers = EXPECTED_N_WRITERS[dataset]
            if boot["n_test_writers"] != expected_writers:
                print(f"[STOP] {dataset}/{metric_name}: n_test_writers="
                      f"{boot['n_test_writers']}, expected {expected_writers}.")
                return 1

            # ---- verification 4: paired CI must be narrower than the ----
            # naive combination of the two marginal intervals' extremes.
            r_lo, r_hi = float(marginal_ci[key_r]["ci_lower_2.5pct"]), float(marginal_ci[key_r]["ci_upper_97.5pct"])
            s_lo, s_hi = float(marginal_ci[key_s]["ci_lower_2.5pct"]), float(marginal_ci[key_s]["ci_upper_97.5pct"])
            naive_lo, naive_hi = r_lo - s_hi, r_hi - s_lo
            naive_width = naive_hi - naive_lo
            paired_width = boot["ci_hi"] - boot["ci_lo"]
            if paired_width > naive_width:
                print(f"[STOP] {dataset}/{metric_name}: paired interval width "
                      f"({paired_width:.4f}) is WIDER than the naive marginal-"
                      f"extremes width ({naive_width:.4f}) -- pairing looks "
                      f"broken. Not proceeding.")
                return 1

            excludes_zero = boot["ci_lo"] > 0 or boot["ci_hi"] < 0
            rows.append({
                "dataset": dataset,
                "metric": metric_name,
                "resample_unit": "writer",
                "eer_resnet18": eer_resnet18,
                "eer_smallcnn": eer_smallcnn,
                "observed_diff": observed_diff,
                "diff_ci_lower_2.5pct": boot["ci_lo"],
                "diff_ci_upper_97.5pct": boot["ci_hi"],
                "frac_iterations_resnet18_worse": boot["frac_resnet18_worse"],
                "n_resamples": boot["n_valid_iterations"],
                "n_test_writers": boot["n_test_writers"],
                "n_pairs": int(mask.sum()),
            })
            verdict = "EXCLUDES zero (statistically supported difference)" if excludes_zero \
                else "includes zero (no statistically supported difference)"
            print(f"  {metric_name}: EER resnet18={eer_resnet18:.4f} smallcnn={eer_smallcnn:.4f} "
                  f"diff={observed_diff:+.4f}  95% CI=[{boot['ci_lo']:+.4f}, {boot['ci_hi']:+.4f}]  "
                  f"P(resnet18 worse)={boot['frac_resnet18_worse']:.3f}  "
                  f"n_writers={boot['n_test_writers']} n_pairs={int(mask.sum())}")
            print(f"    -> {verdict}  [paired width={paired_width:.4f} vs "
                  f"naive marginal-extremes width={naive_width:.4f}]")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    fieldnames = ["dataset", "metric", "resample_unit", "eer_resnet18", "eer_smallcnn",
                 "observed_diff", "diff_ci_lower_2.5pct", "diff_ci_upper_97.5pct",
                 "frac_iterations_resnet18_worse", "n_resamples", "n_test_writers", "n_pairs"]
    with out_path.open("w", newline="", encoding="utf-8") as fh:
        w = csv.DictWriter(fh, fieldnames=fieldnames)
        w.writeheader()
        for r in rows:
            w.writerow(r)
    print(f"\n[out] wrote {out_path}")

    # ---- readable stdout table -------------------------------------------
    header = (f"| {'dataset':17} | {'metric':12} | {'diff':8} | {'95% CI':21} | "
             f"{'P(r18 worse)':12} | {'excludes 0':10} |")
    print("\n" + header)
    print("|" + "-" * (len(header) - 2) + "|")
    for r in rows:
        ci = f"[{r['diff_ci_lower_2.5pct']:+.4f}, {r['diff_ci_upper_97.5pct']:+.4f}]"
        excl = "yes" if (r["diff_ci_lower_2.5pct"] > 0 or r["diff_ci_upper_97.5pct"] < 0) else "no"
        print(f"| {r['dataset']:17} | {r['metric']:12} | {r['observed_diff']:+.4f} | "
              f"{ci:21} | {r['frac_iterations_resnet18_worse']:12.3f} | {excl:10} |")

    print("\nNote: eer_all and eer_skilled on the same dataset are NOT "
          "independent comparisons (skilled pairs are a subset of all "
          "pairs) -- these six rows are three independent per-corpus "
          "comparisons, not six.")

    return 0


if __name__ == "__main__":
    sys.exit(main())
